### ISSUE TITLE
travis-ciが失敗する

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text_pdf#2]
https://travis-ci.org/dwango/scala_text_pdf/builds/166069918

```
0.01s$ export PATH=$PATH:/usr/texbin
0.03s$ sudo tlmgr update --self --all
sudo: tlmgr: command not found
The command "sudo tlmgr update --self --all" failed and exited with 1 during .
Your build has been stopped.
/Users/travis/build.sh: line 109: shell_session_update: command not found
```

以下のコミットからだが、一文字変えただけなので、おそらく本文の内容の変更が原因ではない
- https://github.com/dwango/scala_text_pdf/commit/2e4d7fc8925b49f3fc82b943d712ddf31163cfac
- https://github.com/dwango/scala_text/compare/dwango:524b15d...dwango:12d5ea3

**Comment by xuwei-k** [comment]
たいして根拠ない(?)原因の予想、その1

http://qiita.com/kdnk/items/1a89b693e11b24b8d8bf これ？travis-ciのosxのversion上がった？(最近上がったのかどうかすら未確認)

**Comment by y-yu** [comment]
まず、OSXのバージョンがあがったことにより失敗したのは間違いないようです。ただ、TeXLiveも同時に壊れているように思われます。

**Comment by xuwei-k** [comment]
slack通知のテストコメント
